services:
  nginx:
    container_name: simple-url-shortener-nginx
    image: nginx:latest
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/web:/web
    ports:
      - "8887:80" # Host:Container
    networks:
      internal_net:
        ipv4_address: 100.100.223.2
    restart: unless-stopped

  python-app:
    container_name: simple-url-shortener-python
    image: python:3.13.1-alpine3.21
    build:
      dockerfile: Dockerfile
    volumes:
      - ./docker/backend:/app
    expose:
      - "8000"
    networks:
      internal_net:
        ipv4_address: 100.100.223.3
    restart: unless-stopped

networks:
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: 100.100.223.0/24